.github/CONTRIBUTING.md
Fix typos in CONTRIBUTING.md
None
Clean up documentation
n/a
n/a
=> docs(CONTRIBUTING.md): update CONTRIBUTING.md

binary_marshaler.go, certificates.go, client.go, config_test.go, health.go, key.go, server.go, server_config.go, server_options.go, tls_credentials.go, tls_provider.go
Refactor TLS support into interfaces and remove disused functions.
Cleanup TLS config
#7
First step in refactoring of Server setup.
=> feat: refactor TLS and server

server.go
Fix server default setup
When we refactored to split apply and addHandler, the running of default options wasn't correct.
=> fix: server default setup

cmd.go
Remove IsNil() check for string error logs
Correctly display error messages
Tested locally with server implementation
=> fix(cmd): allow string error logging

cmd.go
Log error only if value of runner is not nil
Should error only if value of runner is not nil
=> fix(cmd): fix nil error log

server_options.go
=> fix: swagger handler specifying

tls_credentials.go
Change error handling on errors loading certificates.
In the cases where we connect to Vault, if there is a communication error, we might not handle that properly, carrying on with improperly configured certificates.
Improve error handling.
Testing in progress
=> fix: fail on certificate failure

context_credentials.go
Get token from AuthToken in addition to metadata
Support gateways
=> fix(auth): get token from AuthToken

http.go
Add HTTP PATCH method (currently only GET/POST/PUT/DELETE is supported)
N/A
To support any HTTP calls requiring PATCH method
=> feat(patch): add http patch

go.mod, go.sum, server.go, server_config.go
Automatically register the profiler if an environment variable is set
Sometimes easier to do this dynamically instead of code changes or requiring clients to roll their own.
Local server using this code base
=> feat: add profiler based on env variable

client.go, cmd.go, config.go, credentials.go, health.go, http.go, servertest.go, tls_config.go, url_param.go, vault_client.go
Add a beta version of a GRPC test framework. Note no support or backward compatability guarantees provided on this.
N/A
To make it easier to test GRPC services
Using a separate existing service
=> feat: added beta grpc test framework

go.mod, metrics.go, server.go
Fix prometheus setup
Fix panic
=> fix: prometheus setup

http_headers.go
Restore functionality early return if OPTIONS route
#125 
#125 moved CORS header functionality into a helper which changed the return behavior. Restoring such behavior
Ran locally imported into a service (shoreline)
=> fix(options): fix OPTIONS return behavior

http_headers.go, metrics.go, server.go, server_config.go, server_options.go, servertest.go
Fix CORS origin handling to allow specifying allowed origins
N/A
More correct handling of CORS origin
In a server utilizing orlop.
=> fix: cors origin handling

fx.go, log/fx.go
Adds logging, context, and options support for fx
Make it a bit cleaner to setup fx apps
Local
=> feat: add some fx niceness

cmd.go, log/fx.go, server.go
Added the capability to run an fx `Module` directly.
DRY a lot of code
Local
=> feat: add more fx niceness

cert_generation_config.go, certificates.go, client.go, client_config.go, credentials.go, http.go, key.go, key_config.go, server.go, server_config.go, server_options.go, servertest.go, tls_config.go, tls_credentials.go, token_config.go, vault_client.go, vault_config.go
Drop Has* interface usage to ease fx adoption
Slowly migrating to cleaner fx integration
=> feat: drop Has* interface usage to ease fx adoption

go.mod, go.sum, key.go
Fixed enabled check on loading keys
Local
=> fix: bad enabled check

log/fx.go
fx logging needs to change level if error
some error messages weren't being identified as such
Local project
=> fix: fx logging needs to change level if error

log/fx.go, logging/impl.go, logging/level.go, telemetry/module.go, telemetry/telemetry.go
Inject telemetry
Leverage fx and no globals
=> chore: inject telemetry

cmd.go, env/module.go, logging/module.go, logging/setup.go, module.go, parameter/module.go, parameter/store.go, telemetry/module.go, telemetry/telemetry.go
Fix a variety of little bugs from V2
Make V2 work.
Local project.
=> fix: v2 bugs

fx.go
orlop.Populate should take cfg as optional parameter
To allow moving tests to using structless-config
Against an existing service
=> fix: populate should take cfg as optional

errors/configuration.go, errors/forbidden.go, errors/standard.go, request/context.go
=> feat: add forbidden status

errors/permanent.go
Fix handling of `errors.Permanent`
=> fix: permanent

parameter/noop.go
Fix noop object store
Other libraries
=> fix: noop object store

errors/doc.go, errors/internal/not_found.go, errors/internal/parameter.go, errors/internal/source.go, errors/internal/temporary.go, errors/internal/timeout.go, errors/parameter.go, errors/source.go
Add Source and Parameter for error handling
=> feat: add source and parameter error handling

env/environ.go
=> fix: env casing inconsistency

docs/ENVIRONMENT.md
=> feat: add docs

cmd.go, config.go, config/enabled.go, config/file.go, config/reflect.go, context_credentials.go, enabled_config.go, errors/errors.go, file_config.go, fx.go, log/log.go, logging/impl.go, logging/logger.go, module.go, parameter/noop.go, parameter/object_store.go, parameter/store.go
Add `TestModule` and rewrite `Populate` in terms of `TestModule`. Deprecate `Populate`, `FxOptions` and `FxContext`.
=> feat: add TestModule

cmd.go, cmd/cmd.go, fx.go
Add `orlop.Module` and `logging.TraceLevel` to `TestModule`.
=> fix: add module and logging level

errors/canceled.go, errors/code.go, errors/configuration.go, errors/conflict.go, errors/errors.go, errors/forbidden.go, errors/internal/grpc.go, errors/internal/temporary.go, errors/internal/timeout.go, errors/invalid.go, errors/not_found.go, errors/parameter.go, errors/source.go, errors/status_code.go, errors/timeout.go, errors/unavailable.go, errors/user_message.go, go.mod, go.sum
Added various formatting error constructors so you don't have to pass in an `errors.New()`
DRY
=> feat: add errors.*f to provide a formatted error message

errors/code.go, errors/status_code.go
Support code/statusCode from a GRPCStatus object
=> feat: support code/statusCode from a GRPCStatus object

errors/code.go, errors/convert.go, errors/internal/convert.go, errors/internal/mapping.go, errors/internal/standard.go, errors/internal/status_code.go, errors/standard.go, errors/unimplemented.go
DRY StatusCode
Added Convert
Added extensible converters for other libraries to register functions that can convert their errors to standard errors
DRY
=> refactor: DRY status code and add converters to extend error conversion

errors/internal/standard.go, errors/user_message.go
Return underlying error if no user message
=> fix: return underlying error if no user message

request/context.go
=> feat: add request originator

errors/convert.go, errors/internal/convert.go, request/context.go
=> fix: error precedence

request/context.go
=> fix: remove random fizz-buzz noise injected by old breakwater

request/context.go
=> fix: flag url as high cardinality

identity.go
Add `Identity*` and `IgnoreError` and `PanicOnError` helpers
Local
N/A
=> feat: add Identity* and IgnoreError/PanicOnError helpers

errors/internal/mapping.go
Timeout should map to gateway timeout
Another project.
N/A
=> fix: timeout should map to gateway timeout

config/impl.go
Handle case with an empty prefix
Locally in an affected project.
=> fix: handle empty prefix

request/context.go, request/context_test.go
> Helper to clone context 
Unit tested.
=> chore(context): Allow for cloning context

errors/internal/mapping.go
Fix typo in grpc status code mapping
Pulled into testing in supercargo/figurehead gateway
=> chore: fix typo grpc status code

request/context.go
Add context interface
Unit tests
=> feat: add context interface

log/context.go, log/log.go
=> feat: add log context

request/context.go
> added integrationKey to context
=> chore: added integrationKey to context

request/context.go
Add maps for compatibility
Locally
=> fix: add maps for compatibility
